version: '3.1'

services:
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: myapp_root_password

  minio:
    image: quay.io/minio/minio
    restart: always
    tty: true
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: myapp
      MINIO_ROOT_PASSWORD: myapp_root_password
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"
